### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by sreisser** [srnas/barnaba#47]
Hi Sandro,

I'm having a problem installing barnaba in python3.9:
Installation initially seems fine:

----
pip install barnaba
Requirement already satisfied: barnaba in /home/sabine/.local/lib/python3.9/site-packages (0.1.7)
Requirement already satisfied: numpy in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from barnaba) (1.22.3)
Requirement already satisfied: mdtraj in /home/sabine/.local/lib/python3.9/site-packages (from barnaba) (1.9.7)
Requirement already satisfied: future in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from barnaba) (0.18.2)
Requirement already satisfied: scipy in /home/sabine/.local/lib/python3.9/site-packages (from barnaba) (1.8.0)
Requirement already satisfied: astunparse in /home/sabine/.local/lib/python3.9/site-packages (from mdtraj->barnaba) (1.6.3)
Requirement already satisfied: pyparsing in /home/sabine/.local/lib/python3.9/site-packages (from mdtraj->barnaba) (3.0.8)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from astunparse->mdtraj->barnaba) (0.37.1)
Requirement already satisfied: six<2.0,>=1.6.1 in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from astunparse->mdtraj->barnaba) (1.16.0)
----

But when I try to run it, I get an error:

----
(barnaba) sabine@sabine-Swift-SF314-511:~/bin$ barnaba
Traceback (most recent call last):
  File "/home/sabine/.local/bin/barnaba", line 16, in <module>
    from barnaba import commandline
  File "/home/sabine/.local/lib/python3.9/site-packages/barnaba/__init__.py", line 3, in <module>
    from .functions import *
  File "/home/sabine/.local/lib/python3.9/site-packages/barnaba/functions.py", line 19, in <module>
    import mdtraj as md
  File "/home/sabine/.local/lib/python3.9/site-packages/mdtraj/__init__.py", line 55, in <module>
    from ._lprmsd import lprmsd
ImportError: /home/sabine/.local/lib/python3.9/site-packages/mdtraj/_lprmsd.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv
----

Do you have any idea how to fix this?

Cheers
Sabine

**Comment by sbottaro** [comment]
Hi Sabine,


Have you tried to import mdtraj alone? maybe the problem is related to lprmsd?



________________________________
From: sreisser ***@***.***>
Sent: 14 April 2022 10:25:42
To: srnas/barnaba
Cc: Subscribed
Subject: [srnas/barnaba] Installation problem (Issue #47)


Hi Sandro,

I'm having a problem installing barnaba in python3.9:
Installation initially seems fine:

________________________________
pip install barnaba
Requirement already satisfied: barnaba in /home/sabine/.local/lib/python3.9/site-packages (0.1.7)
Requirement already satisfied: numpy in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from barnaba) (1.22.3)
Requirement already satisfied: mdtraj in /home/sabine/.local/lib/python3.9/site-packages (from barnaba) (1.9.7)
Requirement already satisfied: future in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from barnaba) (0.18.2)
Requirement already satisfied: scipy in /home/sabine/.local/lib/python3.9/site-packages (from barnaba) (1.8.0)
Requirement already satisfied: astunparse in /home/sabine/.local/lib/python3.9/site-packages (from mdtraj->barnaba) (1.6.3)
Requirement already satisfied: pyparsing in /home/sabine/.local/lib/python3.9/site-packages (from mdtraj->barnaba) (3.0.8)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from astunparse->mdtraj->barnaba) (0.37.1)
Requirement already satisfied: six<2.0,>=1.6.1 in /home/sabine/anaconda3/envs/barnaba/lib/python3.9/site-packages (from astunparse->mdtraj->barnaba) (1.16.0)

But when I try to run it, I get an error:

________________________________
(barnaba) ***@***.***:~/bin$ barnaba
Traceback (most recent call last):
File "/home/sabine/.local/bin/barnaba", line 16, in
from barnaba import commandline
File "/home/sabine/.local/lib/python3.9/site-packages/barnaba/init.py", line 3, in
from .functions import *
File "/home/sabine/.local/lib/python3.9/site-packages/barnaba/functions.py", line 19, in
import mdtraj as md
File "/home/sabine/.local/lib/python3.9/site-packages/mdtraj/init.py", line 55, in
from ._lprmsd import lprmsd
ImportError: /home/sabine/.local/lib/python3.9/site-packages/mdtraj/_lprmsd.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZSt28__throw_bad_array_new_lengthv

Do you have any idea how to fix this?

Cheers
Sabine

**Comment by sreisser** [comment]
yes seems to be with _lprmsd.cpython-39-x86_64-linux-gnu.so
